### ISSUE TITLE
problem with arguments of custom function

### ISSUE THREAD

**Issue by rferraton** [TylerBrinks/SqlParser-cs#15]
I need to use modulo function in my project.

oracle use the function MOD(m,n) instead of % operator used in many other database.
Snowflake use also the MOD function but using the SnowflakeDialect() does not help. 

My current code, that work for many databases is 

```csharp
addenum = new BinaryOp(
new BinaryOp(
new Identifier(distributedkeycolumn),
BinaryOperator.Modulo,
new LiteralValue(new Value.Number(imaxdop.ToString()))),
BinaryOperator.Eq,
new LiteralValue(new Value.Number(i.ToString())));
```

i try to rewrite using this code inspire by unittest https://github.com/TylerBrinks/SqlParser-cs/blob/8363c382ae4f6857788b82138cd3e42fccbed1ca/src/SqlParser.Tests/Dialects/SnowflakeDialectTests.cs#L746  

==> 
```csharp
var modArgs = 
new Sequence<FunctionArg>
	{
		new FunctionArg.Unnamed(new FunctionArgExpression.FunctionExpression(new Identifier(distributedkeycolumn))),
		new FunctionArg.Unnamed(new FunctionArgExpression.FunctionExpression(new LiteralValue(new Value.Number(imaxdop.ToString()))))
	};

BinaryOp addenum = 
new BinaryOp(
		new Function("MOD") { Args = modArgs },
		BinaryOperator.Eq,
		new LiteralValue(new Value.Number(i.ToString()))
);
```

But it does not compile :

Error	CS0200	Property or indexer 'Expression.Function.Args' cannot be assigned to -- it is read only
on **new Function("MOD") { Args = modArgs },**

**Comment by TylerBrinks** [comment]
That's correct, the types are immutable.  [See my explanation here](https://github.com/TylerBrinks/SqlParser-cs/issues/8)
