### ISSUE TITLE
Get actual Field name when we have SUM

### ISSUE THREAD

**Issue by pantonis** [TylerBrinks/SqlParser-cs#19]
Hello I have a question: 

```SELECT SUM(ProfitInUsd) as Profit,
AVG(AmountInUsd) as Total Amount
FROM Client c
INNER JOIN Order o on o.ClientId = c.Id
INNER JOIN Product p on p.Id = o.ProductId

```
How can I get the column name which is ```ProfitInUsd``` and AmountInUsd in the above case?

Thank you

**Comment by TylerBrinks** [comment]
Your example isn't valid SQL given it's missing a SELECT statement and your alias is 2 words "Total Amount"

However, assuming the following SQL, this would extract the function argument name and projection alias.

 var sql = """
          SELECT AVG(AmountInUsd) as Total_Amount 
          FROM Client c 
          INNER JOIN Order o on o.ClientId = c.Id 
          INNER JOIN Product p on p.Id = o.ProductId 
          """;

```
 var parsed = new Parser().ParseSql(sql, new GenericDialect());

 var expr = parsed.Single().AsSelect().Query.Body.AsSelectExpression().Select.Projection
     .First() as SelectItem.ExpressionWithAlias;
 var function = expr.Expression as Function;

 var functionExpr = (function.Args.Single() as FunctionArg.Unnamed).FunctionArgExpression;

// AmountInUsd
 var argValue =((FunctionArgExpression.FunctionExpression)functionExpr).Expression.AsIdentifier().Ident.Value;
// Total_Amount 
 var projectionAlias = expr.Alias;
```
