### ISSUE TITLE
Any plans to implement optimizer/planner for your AST ?

### ISSUE THREAD

**Issue by Degot** [TylerBrinks/SqlParser-cs#2]
Hello, I'm intrested in using this library to add SQL Layer on top of my POCO structures , but I need to implement optimizer/planner/executor on top of your SQL AST. Any plans to implement them?
Do you have any solutions in mind that can be used with this library?

**Comment by TylerBrinks** [comment]
This library is focused on parsing only, not execution.  I have a query engine, but at the moment it is not open source.  There are great resources in reach of a Google query that you can look into for building logical plans, plans, optimization steps, etc...
