### ISSUE TITLE
Expression with SUM in HAVING 

### ISSUE THREAD

**Issue by pantonis** [TylerBrinks/SqlParser-cs#20]
I want to produce this sql query

```
SELECT 
	CountryId,
	SUM(Profit),
	SUM(Tax)	
FROM [Orders]
GROUP BY CountryId
HAVING SUM(Profit) > 0
````
How can I create the expression that contains the ```SUM(Profit)``` to be used in HAVING clause?

**Comment by TylerBrinks** [comment]
I'm unclear what you're trying to do.  Are you trying to parse that query or produce an abstract syntax tree representation?  Can you elaborate?
