### ISSUE TITLE
Databricks (Spark) SQL parsing failure

### ISSUE THREAD

**Issue by michael-damatov** [TylerBrinks/SqlParser-cs#22]
The SQL expression

``` sql
SELECT array('A', 'B', 'C')
```

is perfectly valid in Spark SQL.

The following code
``` cs
new Parser().ParseSql("SELECT array('A', 'B', 'C')", new DatabricksDialect())
```

throws a `ParserException`:
```
Expected SELECT, VALUES, or a subquery in the query body, found 'A', Line: 1, Col: 14
```

**Comment by TylerBrinks** [comment]
The parser supports custom dialects that are not built into library.  Spark is not an inbuilt dialect, and as such you would need to provide a Spark-specific implementation to support a function that's not native to a generic dialect.

https://github.com/TylerBrinks/SqlParser-cs?tab=readme-ov-file#supporting-custom-sql-dialects

**Comment by michael-damatov** [comment]
How to make the `array` function to be recognized as a valid function? I cannot find any method or property to override in the base `Dialect` class.
