### ISSUE TITLE
Failed to parse `INSERT` statement

### ISSUE THREAD

**Issue by lamg** [TylerBrinks/SqlParser-cs#6]
# Steps to reproduce

- build from source https://github.com/lamg/migrate using the `install.sh` script
- execute the following steps

```sh
mkdir mig_project
cd mig_project
mig init
```

- now edit the file `schema.sql` and replace its content by
```sql
CREATE TABLE user(id integer NOT NULL, name text NOT NULL);
create table bla(username text not null);
create table bli(username text not null);

INSERT INTO bla(username)
VALUES ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1'),
       ('value1');

INSERT INTO bli(username)
VALUES ('value0'),
       ('value0'),
       ('value0'),
       ('value0'),
       ('value0'),
       ('value0'),
       ('value0');
```
- now run `mig status`

You should see the following error message

```
Error parsing schema.sql(6,2): Expected SELECT, VALUES, or a subquery in the query body, found VALUES, Line: 6, Col: 2
```

# Possible cause
- the keyword `VALUES` is not found sometimes [here][0] because `Keywords.All` is not sorted.

While debugging the parser I inspected `Keywords.All` and found this:
![Screenshot from 2023-12-22 20-01-59](https://github.com/TylerBrinks/SqlParser-cs/assets/3207821/46269c5f-46c1-4919-b2bc-6f594d6e8036)

`"_" < "I"` evaluates to false

# To consider

- I thought that sorting `Keywords.All` would solve the problem, but then converting [here][1] an index to a `Keyword` doesn't work. The indexes in `Keywords.All` are at that point not corresponding to the proper keyword in the `Keyword` enum.
- For some unknown reason (still puzzling me) I haven't been able to reproduce the error in [this test][2]

[0]: https://github.com/TylerBrinks/SqlParser-cs/blob/2dd53cd0cf4d7df362b9f81343f8bc9800006e02/src/SqlParser/Tokens/Word.cs#L32
[1]: https://github.com/TylerBrinks/SqlParser-cs/blob/2dd53cd0cf4d7df362b9f81343f8bc9800006e02/src/SqlParser/Tokens/Word.cs#L36C38-L36C38
[2]: https://github.com/lamg/migrate/blob/8df8734265703fb0c46337fc6c2c119c1e4c7547/Test/SqlParser.fs#L20

**Comment by TylerBrinks** [comment]
Is there a way to simplify this down to a repeatable error with the SQL parser?  It's not clear that the parser is the error with your passing test.

**Comment by lamg** [comment]
I can simplify the issue to a precondition of `Array.BinarySearch` not holding [here](https://github.com/TylerBrinks/SqlParser-cs/blob/2dd53cd0cf4d7df362b9f81343f8bc9800006e02/src/SqlParser/Tokens/Word.cs#L32). The precondition is that the array should be sorted. When it is not, the return value can be hard to predict, according what I interpret from the `Array.BinarySearch` documentation:

_If this method is called with a non-sorted array, the return value can be incorrect and a negative number could be returned, even if value is present in array._

**Comment by TylerBrinks** [comment]
What I was asking for was a test case that consistently fails from which we can code against. Is it possible to compowe a query that fails independently?

**Comment by TylerBrinks** [comment]
Fix is deployed to NuGet.  I tested your project's branch with the update successfully.
