### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by pantonis** [TylerBrinks/SqlParser-cs#7]
I have tried to use it in a .NET 7 project and I see that is not compatible.

**Comment by TylerBrinks** [comment]
We can evaluate it for previous framework versions, but the intent is to use it with current + future frameworks, not legacy.  Part of the position has to do with using specific memory management features.

**Comment by pantonis** [comment]
Thanks for your reply and I totally understand the reason behind this.
May I ask what are the memory management features that exist in .NET 8 that
don't exist in .NET 7?

**Comment by TylerBrinks** [comment]
Sorry for the confusion.  Not to say features do or don't exist.  I simply haven't had time to test out the ref struct areas (tokenizer, and reader state), or the custom string interpolation in .NET 7.  I'm not at all opposed to targeting multiple frameworks; I just don't perceive a need to target an older, non-LTS version until or unless there's a reason.  I'm happy to take a PR and try it out if you want to add the targeting.  I'll happily deploy it to nuget.org
