### ISSUE TITLE
Question: How to modify existing sql query after parsing 

### ISSUE THREAD

**Issue by pantonis** [TylerBrinks/SqlParser-cs#8]
Hello,

How can we modify existing Sqlquery after we parse it so that it generates a new query with some extra filters we need to do. Are there any examples?

**Comment by TylerBrinks** [comment]
At the moment, queries are immutable like their Rust counterparts.  That may change in the future, but at the moment this library is following the same patterns.  You can easily construct a new instance, however.  You can use the built-in visitor pattern for total control while traversing the object graph.  There are unit test examples that show how visitors work.  However if you simply want to modify an object with updated properties, standard C# syntax works.  For brevity, `with` expressions make it easy.

```
var query = new Parser().ParseSql("select * from location").First().AsQuery();
var select = query.Body.AsSelectExpression();
var from = select.Select.From;

query = query with
{
    Body = select with
    {
        Select = new Select([new SelectItem.UnnamedExpression(new LiteralValue(new Value.SingleQuotedString("abc")))])
        {
            From = from
        }
    }
};
```
