### ISSUE TITLE
Can it only Parser a condition statement?

### ISSUE THREAD

**Issue by Brent-bai** [TylerBrinks/SqlParser-cs#9]
Such as "age > 18 AND name = 'John' OR salary < 50000"

I look up the source code, didnot found the method.
Thanks for your work, it do help me.

**Comment by TylerBrinks** [comment]
Yes, the parser can parse any valid SQL statement.

Try the demo project in the source code.  You can enter your own SQL statement and print out the AST or JSON representation

**Comment by Brent-bai** [comment]
@TylerBrinks 
I mean only the condition which is part of a sql statement.
I Tried the demo, it seems not worked.
```
Enter a SQL Query: age > 18 AND name = 'john' OR salary < 50000
Invalid SQL.
Expected a SQL statement, found >, Line: 1, Col: 5

Continue?
```

**Comment by Brent-bai** [comment]
Since my SQL statement contains variables, I will only parse the part that does not include variables to retrieve the desired information.

**Comment by VbBrasil** [comment]
Hello, Tyler,
I would like to see a code in c# that reads all WHERE clauses where I can build a list with all the words that make up the filter criteria in the WHERE clause.
Thank you so much for all suport.
